log.location: /Users/guohui/temp/log
log.sql.level: info

# 数据库配置
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql


security:
  jwt:
    issuer: myapp
    header: Authorization
    expires-in: 604800
    secret: secret
    base-path: /api/**
    permit-all-paths: /api/auth/**,/public/status,/api/health
    auth-api-enabled: true
    auth-me-path: /api/auth/me
    create-auth-token-path: /api/auth/login
    refresh-auth-token-path: /api/auth/refresh

wfc:
  eventbus:
    corePoolSize: 2
    maxPoolSize: 4
    maxQueueSize: 100
    keepAliveTime: 5