log.location: /Users/guohui/temp/log
log.sql.level: info

# 数据库配置
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
